version: "3.7"
services:
    vite:
        image: node:alpine
        container_name: vite
        entrypoint: /bin/sh
        ports:
            - 8000:8000
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - node_modules:/usr/src/app/node_modules
        tty: true

    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ${PWD}/docker/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ${PWD}/docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ${PWD}/docker/php/bin:/var/bin
            - ${PWD}/backup/public:/backup/public
        networks:
            - main

    db:
        image: mysql:latest
        volumes:
            - ${PWD}/docker/mysql/db:/var/lib/mysql
            - ${PWD}/docker/mysql/bin:/var/bin
            - ${PWD}/backup/db:/backup/db
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - ${DATABASE_HOST_PORT}:3306
        networks:
            - main

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - ${NGINX_HOST_HTTP_PORT}:80
        volumes:
            - ./:/var/www
            - ${PWD}/docker/nginx/conf.d:/etc/nginx/conf.d
            - ${PWD}/docker/nginx/logs:/var/log/nginx
        depends_on:
            - app
        networks:
            - main

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        environment:
            - REDIS_PASSWORD=121212
        command: [ "redis-server", "--requirepass", "121212", "--appendonly", "yes" ]
        volumes:
            - redis_data:/data
        networks:
            - main

networks:
  main:
      driver: bridge

volumes:
    node_modules:
    redis_data:
