version: "3.7"
services:
  vite:
    image: node:alpine
    container_name: vite
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /var/www/
    volumes:
      -   type: bind
          source: ./
          target: /var/www/
    tty: true

  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ${PWD}/docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ${PWD}/docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ${PWD}/docker/php/bin:/var/bin
      - ${PWD}/backup/public:/backup/public
      - /srv/sshfs:/var/www/storage/app/public
    networks:
      - main

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./:/var/www
      - ${PWD}/docker/nginx/conf.d:/etc/nginx/conf.d
      - ${PWD}/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/docker/nginx/logs:/var/log/nginx
      - /srv/sshfs:/var/www/storage/app/public
    depends_on:
      - app
    networks:
      - main

networks:
  main:
    driver: bridge
